# My workflow
name: workflow1

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: | 
          echo "hello from raju"
          ls-l
          hostname
      - name: step2
        run: sleep 30
job2:
  runs-on: ubuntu-latest
  steps:
    - name: copy from gitflow
      uses: actions/checkout@v4.1.1
      run: |
        echo "hello from raju"
        ls-l
        
      
  

  
